name: ewe
version: 0.2.0.1
synopsis:            An language using in Programming Languages teaching
description:         Another implemention of the EWE programming language originally created and developed by Kent D. Lee. EWE is an extension of the RAM programming language. RAM was created by Sethi.
homepage:            http://github.com/jfcmacro/ewe
license:             BSD3
license-file:        LICENSE
author:              Juan Francisco Cardona McCormick
maintainer:          fcardona@eafit.edu.co
category:            Language

extra-source-files:
   - src-ag/Language/EWE/CheckGrammar.ag
   - src-ag/Language/EWE/PPProg.ag
   - src-ag/Language/EWE/AbsSyn.ag

dependencies:
 - uuagc-cabal >= 1.1.0.0
 - uulib >= 0.9.23
 - uuagc >= 0.9.52.1
