name:                ewe
version:             0.1.0.45
github:              "jfcmacro/ewe"
license:             BSD3
author:              "Juan Francisco Cardona Mc'Cormick"
maintainer:          "fcardona@eafit.edu.co"
copyright:           "2017 Juan Francisco Cardona Mc'Cormick"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/ewe#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  ewe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ewe

tests:
  ewe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ewe
